#!/bin/bash

cut -f2 -d" " inimesed.txt | cut -f1 -d";" | tr '[:upper:]' '[:lower:]' > eesnimed.txt
cut -f2 -d":" inimesed.txt | cut -f1 -d"," | tr '[:upper:]' '[:lower:]' > perenimed.txt
cut -f2 -d"-" inimesed.txt | cut -f1 -d" " | tr '[:upper:]' '[:lower:]' > domeenid.txt

paste -d"." eesnimed.txt perenimed.txt > kasutajad.txt
paste -d"@" kasutajad.txt domeenid.txt > meilid.txt
