#!/bin/bash

echo -n "Sisesta mingi täisarv: "

read arv

arv=${arv#-}

summa=0

while [ $arv -ne 0 ]; do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
echo "Sisestatud arvu numbrite summa on:$summa"
