#!/bin/bash
echo "Sisesta enda vanus:"
read vanus
if test $vanus -gt 0 -o $vanus -lt 11
then
	echo "oled laps"
elif test $vanus -gt 11 -o $vanus -lt 18
then
	echo "oled nooruk"
elif test $vanus -gt 18 -o $vanus -lt 63
then
	echo "oled täiskasvanu"
elif test $vanus -ge 63
then
	echo "oled senjoor"
fi
	
