#!/bin/bash

echo "sisesta kuu number"

read number

if test $number -eq 1 -o $number -eq 2 -o $number -eq 12
then
	echo "Praegu on talv"

elif test $number -ge 3 -a $number -le 5
then
	echo "Praegu on kevad"

elif test $number -ge 6 -a $number -le 8
then
	echo "Praegu on Suvi"

elif test $number -ge 9 -a $number -le 11
then
	echo "Praegu on sügis"

else
	echo "antud kuu numbrit ei ole"
fi
